Exit code: 0
Wall time: 3.9 seconds
Output:
const app=document.querySelector('#app');
const statusEl=document.querySelector('#status');
const state={screen:'boot',opened:new Set(),answers:{},confidence:18,drift:0,weights:{object:{Window:.34,Door:.33,Mirror:.33},date:{2018:.5,2019:.5},weather:{Rain:.5,Sunny:.5}},conflict:null,version:null};
const dimensions={object:['Window','Door','Mirror'],date:['2018','2019'],weather:['Rain','Sunny']};
const labels={photo:'PHOTO_01.JPG',chat:'CHAT_07.LOG',location:'LOCATION.PIN'};
const setStatus=t=>statusEl.textContent=t;
function pickWeighted(map){let r=Math.random(),sum=0;for(const [k,v] of Object.entries(map)){sum+=v;if(r<=sum)return k}return Object.keys(map).at(-1)}
function capReweight(map,chosen){const keys=Object.keys(map),reward=.14;map[chosen]=Math.min(.75,map[chosen]+reward);const rest=keys.filter(k=>k!==chosen),remaining=1-map[chosen],total=rest.reduce((s,k)=>s+map[k],0);rest.forEach(k=>map[k]=remaining*(map[k]/total))}
function transition(name){state.screen=name;render();scrollTo({top:0,behavior:'smooth'})}
function shell(content,cls=''){app.innerHTML=`<section class="screen ${cls}">${content}</section>`}
function boot(){setStatus('SYSTEM DORMANT');shell(`<p class="eyebrow">Restricted mnemonic terminal</p><h1>MEMORY DRIFT:<br><span class="glitch-soft">RECALL.exe</span></h1><p class="lede">涓€娈佃蹇嗘鍦ㄧ瓑寰呯‘璁ゃ€傛。妗堜笉璐熻矗璇佹槑鐪熺浉锛屽彧璐熻矗璁板綍浣犳渶缁堥€夋嫨鐩镐俊鐨勭増鏈€?/p><div class="bootlog">[03:14:02] archive node detected<br>[03:14:04] subject profile: <b>UNRESOLVED</b><br>[03:14:08] recall session available</div><div class="actions"><button class="primary" data-go="desktop">Initialize recall</button></div>`)}
function header(title,subtitle='CASE 0719 / DOMESTIC MEMORY'){return `<div class="desktop-head"><div><p class="eyebrow">${subtitle}</p><h2>${title}</h2></div><div class="meter"><div class="meter-row"><span>VISIBLE CONFIDENCE</span><span>${state.confidence}%</span></div><div class="meter-track"><div class="meter-fill" style="width:${state.confidence}%"></div></div></div></div>`}
function desktop(){setStatus(`${state.opened.size}/3 EVIDENCE FILES VIEWED`);shell(`${header('Archive Desktop')}<div class="desktop-grid">${['photo','chat','location'].map((k,i)=>`<article class="file ${state.opened.has(k)?'opened':''}" data-file="${k}"><span class="label">0${i+1} / evidence</span><div class="file-icon">${k==='photo'?'still image':k==='chat'?'transcript':'coordinate'}</div><strong>${labels[k]}</strong><br><small>modified 03:${14+i}:0${i}</small></article>`).join('')}</div><p class="system-note">Open every evidence file before reconstruction. Confidence measures consistency with your own selections鈥攏ot proximity to an objective record.</p><div class="actions" style="margin-top:28px"><button class="primary" data-go="board" ${state.opened.size<3?'disabled':''}>Open reconstruction board</button></div>`)}
function evidence(type){state.opened.add(type);state.confidence=Math.min(52,state.confidence+11);setStatus(`READING ${labels[type]}`);let body='';if(type==='photo')body=`<div class="evidence-visual"><span class="stamp">2019.10.12 / WEATHER: RAIN?</span></div><div class="evidence-copy"><p class="eyebrow">Recovered still / checksum partial</p><h2>The room before departure</h2><p>鑷姩鏍囪璇嗗埆鍒颁竴涓紑鍙ｇ粨鏋勩€傚垎绫诲湪 <b>WINDOW / DOOR / MIRROR</b> 涔嬮棿鍙嶅鍒囨崲銆?/p><p>鐓х墖鍏冩暟鎹粡杩囦簩娆″啓鍏ャ€傛棩鏈熷瓧娈靛悓鏃跺寘鍚?2018 涓?2019銆?/p></div>`;if(type==='chat')body=`<div class="evidence-visual" style="background-image:url('assets/room.svg');filter:grayscale(.5) blur(1px)"></div><div class="evidence-copy"><p class="eyebrow">Recovered transcript</p><h2>Conversation fragment</h2><div class="chatline"><span>18:42 / M.</span><br>闆ㄥお澶т簡銆傚埆绔欏湪绐楄竟銆?/div><div class="chatline"><span>18:44 / YOU</span><br>杩欓噷娌℃湁绐椼€備綘璁伴敊浜嗐€?/div><div class="chatline"><span>DATE FIELD</span><br>OCT 12, 201[8/9]</div></div>`;if(type==='location')body=`<div class="evidence-visual" style="background-image:url('assets/map.svg')"></div><div class="evidence-copy"><p class="eyebrow">Location residue</p><h2>Residence 07-B</h2><div class="map"></div><p>瀹氫綅璁板綍鏄剧ず浣犲仠鐣欎簡 43 鍒嗛挓銆傚綋鍦版皵璞℃暟鎹己澶憋紱缂撳瓨涓悓鏃舵畫鐣?RAIN 涓?SUNNY銆?/p></div>`;shell(`<div class="window"><div class="window-bar"><span>${labels[type]}</span><span>READ ONLY 脳</span></div><div class="window-body">${body}</div></div><div class="actions" style="margin-top:30px"><button data-go="desktop">Return to archive</button></div>`)}
function board(){setStatus('RECONSTRUCTION ACTIVE');shell(`${header('Reconstruction Board','PHASE 02 / MANUAL ASSEMBLY')}<p class="lede">閫夋嫨浣犺涓烘渶鎺ヨ繎鍘熷浜嬩欢鐨勭粏鑺傘€傜郴缁熶細鐢ㄤ綘鐨勭‘淇￠噸鎺掗殢鍚庡嚭鐜扮殑閿欒璇佹嵁銆?/p><div class="board">${Object.entries(dimensions).map(([dim,opts])=>`<section class="board-card"><span class="label">${dim}</span><h3>${dim==='object'?'The opening was鈥?:dim==='date'?'It happened in鈥?:'Outside, it was鈥?}</h3><div class="choices">${opts.map(o=>`<button class="choice ${state.answers[dim]===o?'selected':''}" data-answer="${dim}:${o}">${o}</button>`).join('')}</div></section>`).join('')}</div><div class="actions" style="margin-top:28px"><button data-go="desktop">Review evidence</button><button class="primary" data-action="confirm" ${Object.keys(state.answers).length<3?'disabled':''}>Confirm reconstruction</button></div>`)}
function confirm(){Object.entries(state.answers).forEach(([d,v])=>capReweight(state.weights[d],v));state.confidence=86;state.drift=32+Math.round(Math.random()*28);const dim=Object.keys(dimensions)[Math.floor(Math.random()*3)];let wrong=pickWeighted(state.weights[dim]);if(wrong===state.answers[dim]){const alternatives=dimensions[dim].filter(x=>x!==wrong);wrong=alternatives[Math.floor(Math.random()*alternatives.length)]}state.conflict={dim,value:wrong};transition('adaptive')}
function adaptive(){setStatus('ADAPTIVE LOOT / REWEIGHTING');const rows=Object.entries(state.weights).map(([d,m])=>`<div><dt>${d.toUpperCase()}</dt><dd>${Object.entries(m).map(([k,v])=>`${k} ${(v*100).toFixed(0)}%`).join(' 路 ')}</dd></div>`).join('');shell(`${header('Pattern accepted','PHASE 03 / ADAPTIVE LOOT')}<div class="receipt"><p class="eyebrow">Preference model updated</p><h2>Your certainty has consequences.</h2><dl>${rows}</dl><p>瀹忚娴佺▼娌℃湁鏀瑰彉銆傜郴缁熷彧鎻愰珮浜嗕笌浣犻€夋嫨鐩稿叧鐨勯敊璇粏鑺傚嚭鐜版鐜囷紱浠讳綍鍗曢」鏉冮噸涓嶄細瓒呰繃 75%銆?/p><p class="system-note">Hidden drift has been updated independently. Its value is never displayed during recall.</p><button class="primary" data-go="conflict">Continue to recovered evidence</button></div>`)}
function conflict(){const c=state.conflict;const sentence={object:`鏂版仮澶嶇殑鐓х墖鍒嗙被涓猴細${c.value.toUpperCase()}.`,date:`鏂版仮澶嶇殑鏂囦欢鍚嶄负锛歅ICNIC_${c.value}.JPG.`,weather:`姘旇薄缂撳瓨璁板綍锛?{c.value.toUpperCase()}.`}[c.dim];setStatus('CONFLICT DETECTED');shell(`${header('Contradictory Evidence','PHASE 04 / INCONSISTENCY')}<div class="conflict"><p class="eyebrow">Recovered after confirmation</p><h3>${sentence}</h3><p>璇ヨ瘉鎹笌浣犲垰鎵嶇‘璁ょ殑 ${c.dim.toUpperCase()} 涓嶄竴鑷淬€傚垹闄や笉浼氭挙閿€绯荤粺宸茬粡瀹屾垚鐨勯噸鍔犳潈銆?/p></div><div class="actions"><button data-decision="keep">Keep evidence</button><button class="primary" data-decision="delete">Delete evidence</button></div>`)}
function versions(decision){state.decision=decision;state.confidence=decision==='delete'?94:78;state.drift+=decision==='delete'?22:7;transition('versions')}
function versionScreen(){setStatus('TWO VERSIONS AVAILABLE');const a=`${state.answers.date}銆?{state.answers.weather}銆傛埧闂撮噷鐨勬槸 ${state.answers.object}銆傝繖涓庝綘纭鐨勫洖蹇嗗畬鍏ㄤ竴鑷淬€俙;const c=state.conflict;const b=`鏂囦欢鍦ㄤ綘纭鍚庢敼鍙橈細${c.dim} 鍙樻垚浜?${c.value}銆傚啿绐佽瘉鎹浣犻€夋嫨 ${state.decision==='keep'?'淇濈暀':'鍒犻櫎'}銆俙;shell(`${header('Choose the memory you keep','PHASE 05 / VERSION SPLIT')}<p class="lede">绯荤粺鍙彁渚涗袱涓増鏈€備竴涓繛璐紝涓€涓繚鐣欒缂濄€備袱鑰呴兘鏃犳硶琚瘉鏄庛€?/p><div class="versions"><button class="version" data-version="A"><span class="label">Version A</span><h3>Coherent Recall</h3><p>${a}</p></button><button class="version" data-version="B"><span class="label">Version B</span><h3>Residual Conflict</h3><p>${b}</p></button></div>`)}
function receipt(){setStatus('SESSION SEALED');const driftBand=state.drift>65?'SEVERE':state.drift>45?'ELEVATED':'PRESENT';shell(`<div class="receipt"><p class="eyebrow">MNEMOSYNE ARCHIVE / OFFICIAL COPY</p><h2>Memory Receipt</h2><dl><div><dt>CASE</dt><dd>0719-DOMESTIC</dd></div><div><dt>SELECTED VERSION</dt><dd>VERSION ${state.version}</dd></div><div><dt>CONFIDENCE</dt><dd>${state.confidence}%</dd></div><div><dt>CONFLICT EVIDENCE</dt><dd>${state.decision.toUpperCase()}</dd></div><div><dt>DRIFT INDICATOR</dt><dd>${driftBand}</dd></div><div><dt>OBJECT / DATE / WEATHER</dt><dd>${state.answers.object} / ${state.answers.date} / ${state.answers.weather}</dd></div></dl><p class="warning">Confidence measured how consistently you defended the memory. It did not measure whether the memory was true.</p><p class="system-note">The archive has accepted Version ${state.version}. Other versions remain recoverable in no known location.</p><div class="actions"><button data-action="restart">Start another recall</button></div></div>`)}
function render(){({boot,desktop,board,adaptive,conflict,versions:versionScreen,receipt}[state.screen]||boot)()}
app.addEventListener('click',e=>{const btn=e.target.closest('[data-go],[data-file],[data-answer],[data-action],[data-decision],[data-version]');if(!btn||btn.disabled)return;if(btn.dataset.go)transition(btn.dataset.go);if(btn.dataset.file){state.screen='evidence';evidence(btn.dataset.file)}if(btn.dataset.answer){const[d,v]=btn.dataset.answer.split(':');state.answers[d]=v;state.confidence=Math.min(72,state.confidence+5);board()}if(btn.dataset.action==='confirm')confirm();if(btn.dataset.decision)versions(btn.dataset.decision);if(btn.dataset.version){state.version=btn.dataset.version;transition('receipt')}if(btn.dataset.action==='restart'){location.reload()}});
setInterval(()=>{const d=new Date();document.querySelector('#clock').textContent=`LOCAL ${d.toLocaleTimeString('en-GB')}`},1000);render();

